create extension if not exists "uuid-ossp";

create table USERS(
    USER_KEY uuid not null PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    EMAIL_ID VARCHAR(30) NOT NULL,
    ADDRESS1 VARCHAR(30) NOT NULL,
    ADDRESS2 VARCHAR(30) NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    STATE VARCHAR(30) NOT NULL,
    ZIP_CODE INTEGER NOT NULL
);

create table USER_ORDER(
    USER_ORDER_KEY uuid not null PRIMARY KEY,
    USER_ID VARCHAR(30) NOT NULL,
    ORDER_ID Long,
    ORDER_TOTAL DECIMAL(10, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR(30) NOT NULL,
    PAYMENT_KEY uuid,
    STATUS VARCHAR(30) NOT NULL
);


