version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: userDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - capstone-project
    ports:
      - "5435:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bhag1988/user-service:v1.0
    container_name: user-service_container
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 
    ports:
      - "8093:8093"
    networks:
      - capstone-project

networks:
  capstone-project:

volumes:
  postgres-data:
